# Generated by Django 5.0.2 on 2024-02-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='key',
        ),
    ]
